#pragma once

#pragma warning(disable : 4819)
#pragma warning(disable : 4996)

#define NOMINMAX
#define WIN32_LEAN_AND_MEAN
#ifndef _WIN32_WINNT
#	define _WIN32_WINNT 0x0501
#endif	// #ifndef _WIN32_WINNT
#ifndef WINVER
#	define WINVER 0x0501
#endif	// #ifndef WINVER

#define SPRIG_CONFIG_LIBINFO_MESSAGE
#define SPRIG_CONFIG_MUST_NOMINMAX

//	CONFIG: D3D
#define SPRIG_CONFIG_LIB_D3DX9_USING_RELEASE_BINARY

//	CONFIG: Sprig.DG
//#define SPRIG_DG_CONFIG_DISABLE_THROW_EXCEPTION
//#define SPRIG_DG_CONFIG_DEVICE_MANAGER_ENABLE_OUTPUT_DEVICE_CAPS

//	CONFIG: KTL.Sprites
//#define KTL_SPRITES_CONFIG_USING_STATIC_POINTER_CAST
//#define KTL_SPRITES_CONFIG_PERFORMANCE_TIMER_ENABLE_DEFAULT

//	CONFIG: user config
#define SPRIG_CONFIG_LIB_USERCONFIG
